### ISSUE TITLE
Конфликтующие правила для линтера

### ISSUE THREAD

**Issue by zloidjinn** [umbrik/webtutor-types#14]
Для JSDoc конфликтуют два правила, одно просит прописать типы для @param, второе запрещает их там указывать
![image](https://github.com/umbrik/webtutor-types/assets/20126739/7d2de0c2-cc86-4d5f-8967-4ef1f770a3c5)

**Comment by umbrik** [comment]
[Fixed](https://github.com/umbrik/webtutor-types/commit/983988f8f04ae5d4bad0fe44a327fdf707c3fc17#diff-f688cce16051d8aff8a8911955b69c3b6a7b632ba0ee7f3ecda6791a62078f4dL48)
